### ISSUE TITLE
McCabe Complexity for BOOST_FOREACH

### ISSUE THREAD

**Issue by rriggs** [ideadapt/metriculator#15]
The McCabe complexity for a function using BOOST_FOREACH is 23.  Changing the code to an equivalent for loop results in a McCabe complexity of 4.  Can the McCabe complexity calculations for macros be adjusted?  LSLOC also appears to be calculated with macros expanded.

**Comment by ideadapt** [comment]
You are right, macros are expanded in some extent. To be honest I am not very familiar with that subject at this moment. But I think what you are asking for could be implemented. However, we dont plan to do so. 
But you are very welcome to dive in and contribute your changes :)
