### ISSUE TITLE
list and table viewer bg color on mac

### ISSUE THREAD

**Issue by ideadapt** [ideadapt/metriculator#4]
viewer row bg color on mac is white instead of 'os standart' alternate row color

**Comment by davidgreisler** [comment]
This problem is also there when using Linux (KDE), which is especially bad when you use a dark theme with white text color (white text on white background).

**Comment by ideadapt** [comment]
Thanks for reporting this. I just fixed this issue in pull request #16. It now works on osx. Could you please confirm wether the fix also works on KDE? You should be able to just update your metriculator plugin in eclipse to get the latest version.

**Comment by davidgreisler** [comment]
Thanks for fixing it! :-) Well, although the background color is now correct, there seems to be a new problem. The metrics are gone:
![metriculator fehler](https://f.cloud.github.com/assets/1059882/1275887/e71c4db6-2e17-11e3-8e23-0a74962df876.png)
I went through all view modes, but all are like this.

**Comment by ideadapt** [comment]
I see, okey this is what automatic tests did not cover :) I just rolled back the update site, to the state it was before. I will get into this issue asap and hopefully find a way to get it all working.

**Comment by ideadapt** [comment]
Hi again,
I pushed the new version to the integration update site (http://ideadapt.net/share/metriculator/integration/). It would be really nice if you could install the update from this integration update site and confirm that its now working as expected.

regards
ueli

**Comment by davidgreisler** [comment]
I've tested the new version you posted and it's working here now. 

FYI: I noticed that metrics with warnings are displayed with a yellow background, but also with the default text color (in my case white) which makes them hard to read. For me that isn't a problem because that's just very few classes and I can see the value when I click on them, but I thought you might care. :-)

**Comment by ideadapt** [comment]
Thank you for your feedback! I just released the new version.
